name: "Bug"
description: Something is not behaving as it should
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What is broken?
      placeholder: "e.g. Header overlapping Content on Mobile (< 400px)"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: How to reproduce?
      placeholder: |
        1. Open site on mobile width
        2. scroll down
        3. Header overlapping title
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: What should happen instead?
    validations:
      required: false

  - type: dropdown
    id: where
    attributes:
      label: Where recognized?
      options:
        - "Lokal (dev)"
        - "Vercel Preview"
        - "Production (jannick.me)"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: How bad?
      options:
        - "Cosmetic (can wait)"
        - "Annoying (should be fixed soon)"
        - "Blocking (site looks broken/unprofesional for viewer)"
    validations:
      required: true
