name: "Chore / Refactor"
description: Tidy Up, things that should be done
title: "[Chore] "
labels: ["chore"]
body:
  - type: textarea
    id: what
    attributes:
      label: What should be tidied up/changed?
      placeholder: "e.g. change css values"
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why now not later?
      description: Be honest – if there is no real answer know, maybe its only a nice to have later.
    validations:
      required: false

  - type: checkboxes
    id: risk
    attributes:
      label: Checks before Merge
      options:
        - label: Site loading without errors (tested locally)
        - label: Vercel Preview checked
        - label: no visual Layout-breaks on Mobile
