blank_issues_enabled: false
contact_links:
  - name: 📍 Roadmap / Projekt-Board
    url: https://github.com/IchBinJannick/jannick.me/projects
    about: Übersicht über alle offenen Phasen und Meilensteine.
