name: "Content (Blogpost / Project-Entry)"
description: New Blogpost, Case Study or Project-Entry.
title: "[Content] "
labels: ["content"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Kind of Content.
      options:
        - "Blogpost"
        - "Project / Case Study"
        - "About-Site Update"
    validations:
      required: true

  - type: textarea
    id: topic
    attributes:
      label: What's about?
      placeholder: "e.g. How I changed from Vanilla JS to TypeScript."
    validations:
      required: true

  - type: textarea
    id: outline
    attributes:
      label: Broad Outline (Bulletpoints enough)
      placeholder: |
        - Problem
        - What I tried
        - What I've learned
        - Tech-Stack
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Bevor Publishing
      options:
        - label: Spelling/Grammar checked
        - label: Code-Snippets tested (working as intended)
        - label: Pictures/Screenshots integrated (if necessary)
        - label: Checked if readable on Mobile
