name: "Feature"
description: A new feature to build.
title: "[Feature] "
labels: ["feature"]
body:
  - type: textarea
    id: what
    attributes:
      label: What should be build?
      description: Short and concret. One thing per issue, not "the whole projet site".
      placeholder: "e.g. Navigation in <site-header> with active site linking."
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why? / Which problem does this solve?
      placeholder: "e.g. at this point there is no way to navigate through the site"
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Done, if...
      description: 2-4 concrete, tickable criterion. Compass, noticing when to stop.
      placeholder: |
        - [ ] Links to Home/Projects/About/Contact
        - [ ] active Link visually noticed
        - [ ] working on mobile
    validations:
      required: true

  - type: dropdown
    id: phase
    attributes:
      label: Phase
      description: Does it fit in the current Phase or is it better for later or Nice-To-Have.
      options:
        - "Phase 0 – Fundament (HTML/CSS/JS)"
        - "Phase 1 – Tooling/TypeScript"
        - "Phase 2 – React"
        - "Phase 3 – Next.js"
        - "Later/ Nice-to-have"
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Estimated Size
      description: Be honest, if its too big, maybe splitting it on other issues is better.
      options:
        - "Small (< 1 Hour)"
        - "Medium (1-3 Hours)"
        - "Big (> 3 Hours – maybe split!)"
    validations:
      required: true
